// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafka.proto

//定义包名.

package kafka

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//定义参数
type MessageRequest struct {
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	ClientId             string   `protobuf:"bytes,3,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	MessageBody          []byte   `protobuf:"bytes,5,opt,name=MessageBody,proto3" json:"MessageBody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68928ed13de9fb92, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MessageRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *MessageRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *MessageRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MessageRequest) GetMessageBody() []byte {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

type MessageResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	MessageId            string   `protobuf:"bytes,3,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68928ed13de9fb92, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "kafka.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "kafka.MessageResponse")
}

func init() { proto.RegisterFile("kafka.proto", fileDescriptor_68928ed13de9fb92) }

var fileDescriptor_68928ed13de9fb92 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x1d, 0xb7, 0xab, 0x76, 0xda, 0xaa, 0x0c, 0x28, 0xa1, 0x78, 0x58, 0xf6, 0xb4, 0xa7,
	0x22, 0xfa, 0x02, 0xe2, 0x9e, 0x4a, 0x29, 0x94, 0x15, 0xbc, 0x79, 0xd8, 0x9a, 0xb1, 0x86, 0x2e,
	0x9b, 0xba, 0x49, 0x0e, 0x7d, 0x11, 0xf1, 0x71, 0x65, 0xd3, 0xb4, 0xda, 0x1e, 0x7b, 0x9b, 0xff,
	0xcb, 0x24, 0x7c, 0xfc, 0xc1, 0xde, 0xb2, 0xfc, 0x58, 0x96, 0xa3, 0x55, 0xa3, 0xad, 0xa6, 0xd8,
	0x87, 0xf4, 0x07, 0xf0, 0x72, 0xca, 0xc6, 0x94, 0x0b, 0x2e, 0xf8, 0xcb, 0xb1, 0xb1, 0x24, 0xf0,
	0xfc, 0x95, 0x1b, 0xa3, 0x74, 0x2d, 0x20, 0x81, 0x2c, 0x2e, 0xb6, 0x91, 0xee, 0xb0, 0x1b, 0x76,
	0xc7, 0x52, 0x9c, 0x26, 0x90, 0x75, 0x8b, 0x3f, 0x40, 0x43, 0xbc, 0xc8, 0x2b, 0xc5, 0xb5, 0x1d,
	0x4b, 0x11, 0xf9, 0xc3, 0x5d, 0xa6, 0x6b, 0x8c, 0x26, 0xbc, 0x16, 0x1d, 0x8f, 0xdb, 0x91, 0x12,
	0xec, 0x85, 0xab, 0xcf, 0x5a, 0xae, 0x45, 0x9c, 0x40, 0xd6, 0x2f, 0xfe, 0xa3, 0xf4, 0x0d, 0xaf,
	0x76, 0x66, 0x66, 0xa5, 0x6b, 0xc3, 0x44, 0xd8, 0xc9, 0xb5, 0xe4, 0xe0, 0xe5, 0xe7, 0x56, 0x37,
	0xac, 0x05, 0xa5, 0x6d, 0xdc, 0xd7, 0x8d, 0x0e, 0x74, 0x1f, 0xbe, 0x01, 0x07, 0x93, 0xb6, 0x83,
	0x59, 0xa3, 0xa5, 0x7b, 0xe7, 0x86, 0x9e, 0x70, 0xf0, 0xa2, 0xea, 0x45, 0xc5, 0x33, 0x37, 0xaf,
	0x94, 0xf9, 0xa4, 0x9b, 0xd1, 0xa6, 0xb1, 0xfd, 0x82, 0x86, 0xb7, 0x87, 0x78, 0x63, 0x97, 0x9e,
	0x50, 0x8e, 0xfd, 0xa9, 0xab, 0xac, 0x3a, 0xf6, 0x81, 0x0c, 0xee, 0x61, 0x7e, 0xe6, 0x3f, 0xe8,
	0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xff, 0xf0, 0x59, 0xaf, 0x01, 0x00, 0x00,
}
